### ISSUE TITLE
发送失败的数据不处理，不会造成数据库无限增长么

### ISSUE THREAD

**Issue by hiliving** [ccj659/JJEvent#4]
如果发送失败，数据库不会删除，日积月累，这部分数据会越来越庞大，不考虑这种情况？

**Comment by ccj659** [comment]
设计的初衷 为了最大保证数据不会丢失. 
为什么会发送失败? 无非就是三种情况1.接收方出现问题,2.网络不通.3在SDK内部数据库取出到json序列化出现问题.

针对第一种,为了避免数据累计太大, 我们服务器做的处理是, 无论我们客户端数据怎么样,是否符合规定. 都要返回上传成功. 数据清洗,数据检查的工作, 会在服务器端进行.  这样就保证了, 客户端没有数据累计的现象, 如果有好的思路,可以提一个pull Request 或者 issues 一起探讨.

针对第二种, 一款APP产品, 没有网络就没有时效性的价值, APP都无法正常运行, 数据收集就更不用谈了..

针对对三种, 项目已经正常运行了将近一年的时间.BI反馈 运转正常. 如果在序列化阶段出现问题, 目前项目没有做标记和处理. 需要优化, 近期我会,在release版本中,优化第三种情况.等处理完毕, 我会第一时间通知您~
